### ISSUE TITLE
Unable to get data from API @XposedOrNot

### ISSUE THREAD

**Issue by rishh01** [rishh01/XposedOrNot-App#1]
When calling API to get data for a single email address, API works fine, but while trying to call it dynamically from the user insertion, it cannot get the data from API. @XposedOrNot @DevaOnBreaches @jbhv12

**Comment by DevaOnBreaches** [comment]
Can you please share the exact output or HTTP code you observe when you call the route dynamically ?

**Comment by rishh01** [comment]
Error: Exception: Failed to load data from API.
To double-check I tried the API endpoint with the same email I passed within the text field, then it worked fine.

**Comment by DevaOnBreaches** [comment]
This looks like an exception at your application level. 

As a next step, and to isolate the issue try running the complete API route in a browser or console and check if you get the response properly. If you get the response with content, then the API works fine else share me the HTTP code and a snip of the sample email to verify at API end.

Then you will have to go back to the application and start your debugging to rectify.

Share  your output from the console and feedback and maybe you can take it forward from there.

**Comment by rishh01** [comment]
The API is working fine in the browser. I am now being unsure about the code that I wrote. If possible, could you please check if the code for the API call is correct in the HomePage.dart file?

**Comment by DevaOnBreaches** [comment]
Unfortunately I am not well versed in mobile app development and am not in a position to troubleshoot this.

**Comment by rishh01** [comment]
Okay. Really thankful for your response. I will try to debug it with my peers and some other help.
